#!/usr/bin/env node
// ESM output is now generated by tsc using tsconfig.esm.json
// This file is kept as a no-op placeholder for backwards compatibility
console.log('ESM build: handled by tsc (tsconfig.esm.json)');
